//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhapHang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNHEntities : DbContext
    {
        public QLNHEntities()
            : base("name=QLNHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DVTinh> DVTinh { get; set; }
        public virtual DbSet<tbMatHang> tbMatHang { get; set; }
        public virtual DbSet<tbNhanHang> tbNhanHang { get; set; }
        public virtual DbSet<tbPhieuNhap> tbPhieuNhap { get; set; }
        public virtual DbSet<tbUsers> tbUsers { get; set; }
    }
}
