//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhapHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMatHang
    {
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> MaNhanHang { get; set; }
    
        public virtual tbNhanHang tbNhanHang { get; set; }
    }
}
