//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhapHang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVTinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DVTinh()
        {
            this.tbPhieuNhaps = new HashSet<tbPhieuNhap>();
        }
    
        public int Id { get; set; }
        public string TenDVTinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPhieuNhap> tbPhieuNhaps { get; set; }
    }
}
