//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhapHang.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class QLNHEntities : DbContext
    {
        public QLNHEntities()
            : base("name=QLNHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DVTinh> DVTinhs { get; set; }
        public virtual DbSet<tbDMPhieuNhap> tbDMPhieuNhaps { get; set; }
        public virtual DbSet<tbMatHang> tbMatHangs { get; set; }
        public virtual DbSet<tbNhanHang> tbNhanHangs { get; set; }
        public virtual DbSet<tbPhieuNhap> tbPhieuNhaps { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    }
}
