//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhapHang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDMPhieuNhap
    {
        public string MaPhieuNhap { get; set; }
        public string TongHoaDon { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string MoTa { get; set; }
    
        public virtual tbPhieuNhap tbPhieuNhap { get; set; }
    }
}
