//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhapHang.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMatHang()
        {
            this.tbPhieuNhaps = new HashSet<tbPhieuNhap>();
        }
    
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> MaNhanHang { get; set; }
    
        public virtual tbNhanHang tbNhanHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbPhieuNhap> tbPhieuNhaps { get; set; }
    }
}
